/**
 * Corpus file generator.
 *
 * Regenerate every corpus-owned `.step` file with:
 *
 *   OPENZCAD_WRITE_PARITY_CORPUS=1 pnpm test:parity-corpus
 *
 * Without that env var this file VERIFIES that the committed hand-authored and
 * derived files are still exactly what the generator produces, so a corpus
 * file cannot be edited in place without the suite noticing. Adapter-exported
 * files are not byte-compared — a kernel version bump legitimately changes
 * their bytes, which is why they are committed rather than produced at
 * measurement time.
 *
 * Corpus files are committed on purpose. If they were generated during the
 * measurement run, a kernel regression would silently rewrite the very inputs
 * meant to detect it.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { CommandManager, commandFactories } from '@openzcad/command-system';
import {
  addPrimitiveFeature,
  createBodyFeatureIds,
  createProjectDocument
} from '@openzcad/document-core';
import { toUserId, type BodyId, type ProjectDocument } from '@openzcad/shared';

import { RemusKernelAdapter } from '../../../packages/kernel-adapter/src/exact';
import { OcctStepKernelAdapter } from '../occt-reference/occt-step';

import { CORPUS, MODELING_BASE, REPO_ROOT } from './manifest';
import {
  declareDegreePlaneAngles,
  stripGlobalUnitContext,
  writeBoxStepFile,
  type StepFileSpec
} from './step-authoring';

const WRITE = process.env.OPENZCAD_WRITE_PARITY_CORPUS === '1';
const GENERATOR_USER = toUserId('user_parity_corpus');

/** Files produced by exporting through a kernel; bytes move with the kernel. */
const EXPORTED_IDS = [
  'a-export-box',
  'a-export-cylinder',
  'a-export-cone',
  'a-export-sphere',
  'a-export-bored-plate',
  'e-nurbs-fillet-plate',
  'e-analytic-fillet-plate',
  'f-hostile-occt-authored-box'
] as const;

function corpusPath(id: string): string {
  return join(REPO_ROOT, 'test', 'parity', 'corpus', `${id}.step`);
}

function readCorpus(id: string): string {
  return readFileSync(corpusPath(id), 'utf8');
}

function purposeOf(id: string): string {
  const entry = CORPUS.find((candidate) => candidate.id === id);
  if (!entry) {
    throw new Error(
      `generator emits '${id}' but the manifest does not list it`
    );
  }
  return entry.purpose;
}

/**
 * Corpus files must say what they are. Adapter exports are opaque, so the
 * purpose goes in as a STEP comment at the top of the DATA section — the one
 * place both parsers demonstrably tolerate free text (`scanStepEntities` in
 * `step-import.ts` skips STEP comment blocks, and so do both kernels).
 */
function annotate(id: string, step: string, generated: boolean): string {
  const wrapped = purposeOf(id)
    .replace(/(.{1,70})(\s|$)/g, '   $1\n')
    .trimEnd();
  const lines = [`/* corpus: ${id}`, wrapped];
  if (generated) {
    lines.push(
      '',
      '   Generated by exporting through a kernel adapter. Do not hand-edit;',
      '   rerecord with OPENZCAD_WRITE_PARITY_CORPUS=1 (see corpus/README.md).'
    );
  }
  lines.push('*/');
  const comment = lines.join('\n');
  const dataIndex = step.indexOf('DATA;');
  if (dataIndex < 0) {
    throw new Error(`${id}: exported STEP has no DATA section to annotate`);
  }
  const insertAt = dataIndex + 'DATA;'.length;
  return `${step.slice(0, insertAt)}\n${comment}${step.slice(insertAt)}`;
}

// ---------------------------------------------------------------------------
// Hand-authored files — deterministic, byte-verified on every run
// ---------------------------------------------------------------------------

function authoredFiles(): Array<{ id: string; text: string }> {
  const box = (spec: Omit<StepFileSpec, 'purpose'>) =>
    writeBoxStepFile({ ...spec, purpose: purposeOf(spec.id) });

  return [
    {
      id: 'b-unit-mm-cube',
      text: box({
        id: 'b-unit-mm-cube',
        solids: [
          {
            name: 'Cube',
            outer: {
              min: { x: 0, y: 0, z: 0 },
              max: { x: 25.4, y: 25.4, z: 25.4 }
            }
          }
        ]
      })
    },
    {
      id: 'b-unit-inch-cube',
      text: box({
        id: 'b-unit-inch-cube',
        context: {
          length: { kind: 'conversion', name: 'INCH', factorMm: 25.4 },
          angle: { kind: 'radian' },
          assignUnits: true
        },
        solids: [
          {
            name: 'Cube',
            outer: { min: { x: 0, y: 0, z: 0 }, max: { x: 1, y: 1, z: 1 } }
          }
        ]
      })
    },
    {
      id: 'b-unit-no-global-context',
      text: box({
        id: 'b-unit-no-global-context',
        context: {
          length: { kind: 'millimetre' },
          angle: { kind: 'radian' },
          assignUnits: false
        },
        solids: [
          {
            name: 'Cube',
            outer: { min: { x: 0, y: 0, z: 0 }, max: { x: 20, y: 20, z: 20 } }
          }
        ]
      })
    },
    {
      id: 'c-void-single-cavity',
      text: box({
        id: 'c-void-single-cavity',
        solids: [
          {
            name: 'Hollow cube',
            outer: { min: { x: 0, y: 0, z: 0 }, max: { x: 20, y: 20, z: 20 } },
            voids: [{ min: { x: 5, y: 5, z: 5 }, max: { x: 15, y: 15, z: 15 } }]
          }
        ]
      })
    },
    {
      id: 'c-void-two-cavities',
      text: box({
        id: 'c-void-two-cavities',
        solids: [
          {
            name: 'Twin cavity block',
            outer: { min: { x: 0, y: 0, z: 0 }, max: { x: 30, y: 20, z: 20 } },
            voids: [
              { min: { x: 3, y: 3, z: 3 }, max: { x: 9, y: 9, z: 9 } },
              { min: { x: 16, y: 6, z: 6 }, max: { x: 24, y: 14, z: 14 } }
            ]
          }
        ]
      })
    },
    {
      id: 'd-multi-two-boxes',
      text: box({
        id: 'd-multi-two-boxes',
        solids: [
          {
            name: 'Large box',
            outer: { min: { x: 0, y: 0, z: 0 }, max: { x: 10, y: 10, z: 10 } }
          },
          {
            name: 'Small box',
            outer: { min: { x: 20, y: 0, z: 0 }, max: { x: 26, y: 6, z: 6 } }
          }
        ]
      })
    },
    {
      id: 'd-multi-solid-and-void',
      text: box({
        id: 'd-multi-solid-and-void',
        solids: [
          {
            name: 'Hollow cube',
            outer: { min: { x: 0, y: 0, z: 0 }, max: { x: 20, y: 20, z: 20 } },
            voids: [{ min: { x: 5, y: 5, z: 5 }, max: { x: 15, y: 15, z: 15 } }]
          },
          {
            name: 'Solid box',
            outer: { min: { x: 30, y: 0, z: 0 }, max: { x: 36, y: 6, z: 6 } }
          }
        ]
      })
    },
    {
      id: 'f-hostile-open-shell',
      // The z-max face is dropped from the CLOSED_SHELL member list. The face
      // entity itself stays in the file, so a reader that only counts
      // ADVANCED_FACEs still sees six of them.
      text: dropFaceFromShell(
        box({
          id: 'f-hostile-open-shell',
          solids: [
            {
              name: 'Open box',
              outer: { min: { x: 0, y: 0, z: 0 }, max: { x: 10, y: 10, z: 10 } }
            }
          ]
        }),
        'Open box z-max'
      )
    },
    {
      id: 'f-hostile-dangling-reference',
      text: danglePlaneReference(
        box({
          id: 'f-hostile-dangling-reference',
          solids: [
            {
              name: 'Dangling box',
              outer: { min: { x: 0, y: 0, z: 0 }, max: { x: 10, y: 10, z: 10 } }
            }
          ]
        }),
        'Dangling box z-max'
      )
    },
    {
      id: 'f-hostile-no-shape-representation',
      text: noShapeRepresentationFile()
    },
    { id: 'modeling-base-plate', text: modelingBasePlateText() }
  ];
}

/**
 * The plate every import-modeling scenario is layered on. Kept as a function
 * so the generator's export step can use the same bytes it commits, rather
 * than depending on test execution order.
 */
export function modelingBasePlateText(): string {
  return writeBoxStepFile({
    id: 'modeling-base-plate',
    purpose:
      'The shared base body for the import-modeling scenarios: a ' +
      `${MODELING_BASE.width}x${MODELING_BASE.depth}x${MODELING_BASE.height} mm ` +
      'plate, all planar, so fillet-on-import / boolean-with-import / ' +
      'shell-on-import measure the operation rather than the import.',
    solids: [
      {
        name: 'Plate',
        outer: {
          min: { x: 0, y: 0, z: 0 },
          max: {
            x: MODELING_BASE.width,
            y: MODELING_BASE.depth,
            z: MODELING_BASE.height
          }
        }
      }
    ]
  });
}

/**
 * Files derived by rewriting a committed corpus file. Deterministic given the
 * input, so these are byte-verified too — which is what keeps the degree
 * variants provably the same cone as `a-export-cone`.
 */
function derivedFiles(): Array<{ id: string; text: string }> {
  const degreeCone = annotate(
    'b-unit-degree-cone',
    declareDegreePlaneAngles(stripCorpusComment(readCorpus('a-export-cone'))),
    true
  );
  return [
    { id: 'b-unit-degree-cone', text: degreeCone },
    {
      id: 'b-unit-degree-cone-unassigned',
      text: annotate(
        'b-unit-degree-cone-unassigned',
        stripGlobalUnitContext(stripCorpusComment(degreeCone)),
        true
      )
    }
  ];
}

function stripCorpusComment(step: string): string {
  return step.replace(/\n\/\* corpus:[\s\S]*?\*\//, '');
}

/** Remove one named ADVANCED_FACE from every CLOSED_SHELL that lists it. */
function dropFaceFromShell(step: string, faceName: string): string {
  const face = new RegExp(`#(\\d+)=ADVANCED_FACE\\('${faceName}'`).exec(step);
  if (!face) {
    throw new Error(`no ADVANCED_FACE named '${faceName}' to drop`);
  }
  const id = `#${face[1]}`;
  const dropped = step.replace(
    /CLOSED_SHELL\('([^']*)',\(([^)]*)\)\)/g,
    (_match, label: string, members: string) =>
      `CLOSED_SHELL('${label}',(${members
        .split(',')
        .filter((member) => member !== id)
        .join(',')}))`
  );
  if (dropped === step) {
    throw new Error(`'${faceName}' was not a member of any CLOSED_SHELL`);
  }
  return dropped;
}

/** Point one face's surface at an entity id that is not in the file. */
function danglePlaneReference(step: string, faceName: string): string {
  const pattern = new RegExp(
    `(#\\d+=ADVANCED_FACE\\('${faceName}',\\([^)]*\\),)#\\d+(,\\.[TF]\\.\\);)`
  );
  if (!pattern.test(step)) {
    throw new Error(`no ADVANCED_FACE named '${faceName}' to break`);
  }
  return step.replace(pattern, '$1#999999$2');
}

function noShapeRepresentationFile(): string {
  const purpose = purposeOf('f-hostile-no-shape-representation').replace(
    /'/g,
    "''"
  );
  return [
    'ISO-10303-21;',
    'HEADER;',
    `FILE_DESCRIPTION(('${purpose}'),'2;1');`,
    "FILE_NAME('f-hostile-no-shape-representation.step','2026-01-01T00:00:00',",
    "  ('OpenZCAD parity corpus'),('OpenZCAD'),",
    "  'OpenZCAD parity corpus authoring','OpenZCAD','');",
    "FILE_SCHEMA(('AUTOMOTIVE_DESIGN { 1 0 10303 214 1 1 1 1 }'));",
    'ENDSEC;',
    'DATA;',
    '/* corpus: f-hostile-no-shape-representation',
    '   product structure only: no ADVANCED_BREP_SHAPE_REPRESENTATION and no',
    '   solid anywhere in the file. The refusal message is the whole test. */',
    "#1=APPLICATION_CONTEXT('core data for automotive mechanical design processes');",
    "#2=APPLICATION_PROTOCOL_DEFINITION('international standard','automotive_design',2010,#1);",
    "#3=PRODUCT_CONTEXT('',#1,'mechanical');",
    "#4=PRODUCT('Empty part','Empty part','',(#3));",
    "#5=PRODUCT_DEFINITION_FORMATION('','',#4);",
    "#6=PRODUCT_DEFINITION_CONTEXT('part definition',#1,'design');",
    "#7=PRODUCT_DEFINITION('design','',#5,#6);",
    "#8=PRODUCT_DEFINITION_SHAPE('','',#7);",
    "#9=PRODUCT_RELATED_PRODUCT_CATEGORY('part','',(#4));",
    'ENDSEC;',
    'END-ISO-10303-21;',
    ''
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Adapter-exported files
// ---------------------------------------------------------------------------

function primitiveDocument(
  name: string,
  primitiveKind: 'box' | 'cylinder' | 'cone' | 'sphere',
  dimensions: Record<string, number>
): ProjectDocument {
  return addPrimitiveFeature(
    createProjectDocument(name, GENERATOR_USER, 'mm'),
    {
      name,
      primitiveKind,
      dimensions
    }
  );
}

function boredPlateDocument(): { document: ProjectDocument; bodyId: BodyId } {
  const manager = new CommandManager(
    createProjectDocument('Bored plate', GENERATOR_USER, 'mm')
  );
  const plate = createBodyFeatureIds();
  const bore = createBodyFeatureIds();
  const cut = createBodyFeatureIds();
  manager.runTransaction('Bore the plate', [
    commandFactories.addPrimitive({
      name: 'Plate',
      primitiveKind: 'box',
      dimensions: { width: 40, height: 24, depth: 10 },
      ids: plate
    }),
    commandFactories.addPrimitive({
      name: 'Bore',
      primitiveKind: 'cylinder',
      dimensions: { radius: 5, height: 30 },
      ids: bore
    }),
    commandFactories.transformBody({
      name: 'Seat the bore',
      targetBodyId: bore.bodyId,
      translation: { x: 20, y: 12, z: -10 }
    }),
    commandFactories.booleanBodies({
      name: 'Bored plate',
      operation: 'subtract',
      targetBodyIds: [plate.bodyId, bore.bodyId],
      ids: cut
    })
  ]);
  return { document: manager.document, bodyId: cut.bodyId };
}

/**
 * The four vertical corner edges of the modeling base plate, picked by
 * position exactly the way an interactive edge pick resolves them.
 */
export function verticalCornerEdgeHashes(
  edges: ReadonlyArray<{ hash: number; points: number[] }>,
  height: number
): number[] {
  return edges
    .filter((edge) => {
      const min = [Infinity, Infinity, Infinity];
      const max = [-Infinity, -Infinity, -Infinity];
      for (let index = 0; index < edge.points.length; index += 3) {
        for (let axis = 0; axis < 3; axis += 1) {
          const value = edge.points[index + axis]!;
          min[axis] = Math.min(min[axis]!, value);
          max[axis] = Math.max(max[axis]!, value);
        }
      }
      return (
        max[2]! - min[2]! >= height - 1 &&
        max[0]! - min[0]! < 1 &&
        max[1]! - min[1]! < 1
      );
    })
    .map((edge) => edge.hash);
}

/**
 * A filleted plate built and exported through the given adapter. Remus
 * writes the four fillet bands as B-splines and OCCT writes them as cylinders
 * — the two encodings that make up the (e) category.
 */
async function filletedPlateStep(
  adapter: RemusKernelAdapter | OcctStepKernelAdapter,
  plateStep: string
): Promise<string> {
  const manager = new CommandManager(
    createProjectDocument('Filleted plate', GENERATOR_USER, 'mm')
  );
  const imported = createBodyFeatureIds();
  manager.execute(
    commandFactories.importStep({
      name: 'Plate',
      artifactId: 'artifact_corpus_plate',
      sourceName: 'modeling-base-plate.step',
      stepText: plateStep,
      ids: imported
    })
  );
  const derived = await adapter.syncDocument(manager.document);
  const edges = derived.bodyRepresentations[imported.bodyId]?.topology?.edges;
  if (!edges) {
    throw new Error('base plate imported without topology');
  }
  const corners = verticalCornerEdgeHashes(edges, MODELING_BASE.height);
  if (corners.length !== 4) {
    throw new Error(
      `expected 4 vertical corner edges on the base plate, found ${corners.length}`
    );
  }
  const fillet = createBodyFeatureIds();
  manager.runTransaction('Break the corners', [
    commandFactories.filletEdges({
      name: 'Corner break',
      targetBodyId: imported.bodyId,
      edgeHashes: corners,
      size: 3,
      ids: fillet
    })
  ]);
  await adapter.syncDocument(manager.document);
  return adapter.exportStep(manager.document, [fillet.bodyId]);
}

// ---------------------------------------------------------------------------

describe('parity corpus files', () => {
  let remus: RemusKernelAdapter;
  let occt: OcctStepKernelAdapter;

  beforeAll(async () => {
    if (!WRITE) {
      return;
    }
    remus = new RemusKernelAdapter();
    occt = await OcctStepKernelAdapter.create();
  }, 120_000);

  afterAll(() => {
    remus?.dispose();
    occt?.dispose();
  });

  it.runIf(WRITE)(
    'regenerates the adapter-exported files',
    async () => {
      const plateStep = modelingBasePlateText();

      const produce: Record<
        (typeof EXPORTED_IDS)[number],
        () => Promise<string>
      > = {
        'a-export-box': async () => {
          const document = primitiveDocument('Box', 'box', {
            width: 10,
            height: 20,
            depth: 30
          });
          return remus.exportStep(document, [document.bodyOrder[0]!]);
        },
        'a-export-cylinder': async () => {
          const document = primitiveDocument('Cylinder', 'cylinder', {
            radius: 8,
            height: 20
          });
          return remus.exportStep(document, [document.bodyOrder[0]!]);
        },
        'a-export-cone': async () => {
          const document = primitiveDocument('Cone', 'cone', {
            bottomRadius: 10,
            topRadius: 0,
            height: 10
          });
          return remus.exportStep(document, [document.bodyOrder[0]!]);
        },
        'a-export-sphere': async () => {
          const document = primitiveDocument('Sphere', 'sphere', {
            radius: 6
          });
          return remus.exportStep(document, [document.bodyOrder[0]!]);
        },
        'a-export-bored-plate': async () => {
          const { document, bodyId } = boredPlateDocument();
          await remus.syncDocument(document);
          return remus.exportStep(document, [bodyId]);
        },
        'e-nurbs-fillet-plate': () => filletedPlateStep(remus, plateStep),
        'e-analytic-fillet-plate': () => filletedPlateStep(occt, plateStep),
        'f-hostile-occt-authored-box': async () => {
          const document = primitiveDocument('Box', 'box', {
            width: 10,
            height: 20,
            depth: 30
          });
          return occt.exportStep(document, [document.bodyOrder[0]!]);
        }
      };

      for (const id of EXPORTED_IDS) {
        writeFileSync(corpusPath(id), annotate(id, await produce[id](), true));
      }
    },
    600_000
  );

  it('reproduces every hand-authored file byte for byte', () => {
    for (const { id, text } of authoredFiles()) {
      if (WRITE) {
        writeFileSync(corpusPath(id), text);
        continue;
      }
      expect(
        readCorpus(id),
        `${id}.step differs from what step-authoring.ts produces. Either the ` +
          'file was hand-edited (regenerate it instead) or the authoring ' +
          'helper changed (rerecord with OPENZCAD_WRITE_PARITY_CORPUS=1).'
      ).toBe(text);
    }
  });

  it('reproduces every derived file byte for byte', () => {
    for (const { id, text } of derivedFiles()) {
      if (WRITE) {
        writeFileSync(corpusPath(id), text);
        continue;
      }
      expect(
        readCorpus(id),
        `${id}.step is no longer the documented rewrite of its source file.`
      ).toBe(text);
    }
  });

  it('every manifest entry has a file on disk', () => {
    for (const entry of CORPUS) {
      expect(
        () => readFileSync(join(REPO_ROOT, entry.path), 'utf8'),
        `${entry.id}: ${entry.path} is missing — regenerate with ` +
          'OPENZCAD_WRITE_PARITY_CORPUS=1'
      ).not.toThrow();
    }
    expect(() =>
      readFileSync(join(REPO_ROOT, MODELING_BASE.path), 'utf8')
    ).not.toThrow();
  });

  it('every corpus-owned file names itself in a STEP comment', () => {
    const owned = CORPUS.filter((entry) =>
      entry.path.startsWith('test/parity/corpus/')
    );
    expect(owned.length).toBeGreaterThan(0);
    for (const entry of owned) {
      const text = readCorpus(entry.id);
      expect(
        text.startsWith('ISO-10303-21;'),
        `${entry.id} lost its magic`
      ).toBe(true);
      expect(text, `${entry.id} carries no corpus comment`).toContain(
        `/* corpus: ${entry.id}`
      );
    }
  });

  it('keeps the degree variants provably derived from the same cone', () => {
    const cone = readCorpus('a-export-cone');
    const degree = readCorpus('b-unit-degree-cone');
    const unassigned = readCorpus('b-unit-degree-cone-unassigned');

    const halfAngle = (step: string) =>
      Number(/CONICAL_SURFACE\s*\([^;]*,\s*([\d.E+-]+)\s*\)/i.exec(step)?.[1]);

    expect(halfAngle(cone)).toBeCloseTo(Math.PI / 4, 12);
    expect(halfAngle(degree)).toBeCloseTo(45, 10);
    expect(halfAngle(unassigned)).toBeCloseTo(45, 10);

    // Compare the entity text, not the corpus comment — the comment names the
    // very entity the -unassigned variant is missing.
    const entities = (step: string) => stripCorpusComment(step);
    expect(entities(degree)).toContain('GLOBAL_UNIT_ASSIGNED_CONTEXT');
    expect(entities(degree)).toContain("CONVERSION_BASED_UNIT('DEGREE'");
    // The whole point of the -unassigned variant: no assigned context, so
    // nothing in the file binds a unit and no reader can prove a scale.
    expect(entities(unassigned)).not.toContain('GLOBAL_UNIT_ASSIGNED_CONTEXT');
    expect(entities(unassigned)).toContain("CONVERSION_BASED_UNIT('DEGREE'");
  });
});
